import { Category, CommentU, Destination, Hotel, Province, User, WishList } from "@/models/model";

export const provinces: Province[] = [
    { id: 1, name: "Өмнөговь", image: "/images/provinces/govi.jpg" },
    { id: 2, name: "Завхан", image: "/images/provinces/zavkhan.jpg" },
    { id: 3, name: "Хөвсгөл", image: "/images/provinces/khovsgol.jpg" },
    { id: 4, name: "Баян-Өлгий", image: "/images/provinces/bayanOlgii.jpg" },
    { id: 5, name: "Архангай", image: "/images/provinces/arkhangai.jpg" },
    { id: 6, name: "Увс", image: "/images/provinces/uvs.jpg" },
    { id: 7, name: "Дорнод", image: "/images/provinces/dornod.jpg" },
    { id: 8, name: "Өвөрхангай", image: "/images/provinces/uvurkhangai.jpg" },
    { id: 9, name: "Улаанбаатар", image: "/images/provinces/ulaanbaatar.jpg" },
    { id: 10, name: "Дорноговь", image: "/images/provinces/dornogovi.jpg" },
    { id: 11, name: "Булган", image: "/images/provinces/bulgan.jpg" },
    { id: 12, name: "Хэнтий", image: "/images/provinces/khentii.jpg" },
    { id: 13, name: "Төв", image: "/images/provinces/tuv.jpg" },
    { id: 14, name: "Ховд", image: "/images/provinces/hovd.jpg" },
];

export const categories: Category[] = [
    { id: 1, name: "Hiking" },
    { id: 2, name: "Biking" },
    { id: 3, name: "Climbing" },
    { id: 4, name: "Chilling" },
];

export const hotels: Hotel[] = [
    { id: 1, name: "Hotel One", image: "hotel1.jpg", distance: 2.5, price: 100, rating: 4.2, link: 'link' },
    { id: 2, name: "Hotel Two", image: "hotel2.jpg", distance: 1.2, price: 80, rating: 4.0, link: 'link' },
    { id: 3, name: "Hotel Three", image: "hotel3.jpg", distance: null, price: 120, rating: 4.7, link: 'link' },
];

export const comments: CommentU[] = [
    {
        id: 1,
        rating: 5,
        date: '2025-05-20',
        desc: 'Amazing trip!',
        authorId: 1,
    },
    {
        id: 2,
        rating: 4,
        date: '2025-05-21',
        desc: 'Good experience!',
        authorId: 2,
    },
];


export const destinations: Destination[] = [
    {
        id: 1,
        title: "Алтай Таван Богд",
        overview: "Алтайн нурууны хамгийн өндөр уул.",
        category: [1, 3],   // жишээ hiking
        province: 1,
        images: ["/images/visions/tavanBogd.jpg"],
        location: { lat: 48.0667, lng: 88.0667 },
        sum: "Таван богд сум",
        rating: 4.8,
        filters: ["extreme"],
        comments: null,
        hotels: null,
        isWishListed: false,
    },
    {
        id: 2,
        title: "Ховд гол",
        overview: "Ховд голын үзэсгэлэнтэй газар.",
        category: [2, 3, 4, 1],  // biking жишээ
        province: 2,
        images: ["/images/visions/hovdgol.jpg"],
        location: { lat: 48.0167, lng: 91.6333 },
        sum: "Ховд сум",
        rating: 4.2,
        filters: [],
        comments: null,
        hotels: null,
        isWishListed: false,
    },
    {
        id: 3,
        title: "Цаст Цамбагарав",
        overview: "Цаст уулсын оргил.",
        category: [1,3],  // hiking, climbing
        province: 3,
        images: ["/images/visions/tsambagarav.jpg"],
        location: { lat: 48.2000, lng: 92.3333 },
        sum: "Цамбагарав сум",
        rating: 4.7,
        filters: ["extreme"],
        comments: null,
        hotels: null,
        isWishListed: false,
    },
    {
        id: 4,
        title: "Хорьдол Сарьдагийн нуруу",
        overview: "Сарьдагийн нурууны үзэсгэлэнт газрууд.",
        category: [1],
        province: 4,
        images: ["/images/visions/horidol.jpg"],
        location: { lat: 49.0000, lng: 91.5000 },
        sum: "Сарьдагийн сум",
        rating: 4.3,
        filters: [],
        comments: null,
        hotels: null,
        isWishListed: false,
    },
    {
        id: 5,
        title: "Цагаан нуур",
        overview: "Хөвсгөл аймгийн цэнгэг усны нуур.",
        category: [4],  // chilling
        province: 5,
        images: ["/images/visions/tsagaan.jpg"],
        location: { lat: 49.0000, lng: 100.0000 },
        sum: "Цагаан нуур сум",
        rating: 4.5,
        filters: ["calm"],
        comments: null,
        hotels: null,
        isWishListed: false,
    },
    {
        id: 6,
        title: "Хөвсгөл нуур",
        overview: "Монголын хамгийн гүн нуур.",
        category: [4],
        province: 3,
        images: ["/images/visions/khuvsgul.jpg"],
        location: { lat: 50.2500, lng: 100.5000 },
        sum: "Хөвсгөл сум",
        rating: 4.9,
        filters: ["calm", "extreme"],
        comments: null,
        hotels: null,
        isWishListed: false,
    },
    {
        id: 7,
        title: "Увс нуур",
        overview: "Увс аймгийн байгалийн үзэсгэлэнт нуур.",
        category: [4],
        province: 6,
        images: ["/images/visions/uvs.jpg"],
        location: { lat: 49.9833, lng: 91.6500 },
        sum: "Увс сум",
        rating: 4.4,
        filters: [],
        comments: comments,
        hotels: null,
        isWishListed: false,
    },
    {
        id: 8,
        title: "Хэцүү хад",
        overview: "Уулчдын дуртай хадны маршрут.",
        category: [1,3],
        province: 8,
        images: ["/images/visions/khetsuu.jpg"],
        location: { lat: 48.5000, lng: 90.5000 },
        sum: "Хэцүү хад сум",
        rating: 4.1,
        filters: ["extreme"],
        comments: comments,
        hotels: null,
        isWishListed: false,
    },
];


export const wishLists: WishList[] = [
    {
        id: 1,
        name: "Adventure Places",
        destinations: [1, 2],
        user: 1,
    },
    {
        id: 2,
        name: "Relax Spots",
        destinations: [2],
        user: 1,
    },
    {
        id: 3,
        name: "Future Plans",
        destinations: [],
        user: 1,
    },
    {
        id: 4,
        name: "Short Trips",
        destinations: [1],
        user: 2,
    },
];

export const users: User[] = [
        {
            id: 1,
            name: "User1",
            image: "user1.jpg",
            role: "user",
            username: "user1",
            email: "user1@example.com",
            password: "password123",
            wishLists: [1, 2, 3],
            comments: null,
            isPro: true,
            recently: [destinations[0].id, destinations[1].id],
            messages: ["Hey", "Hello"],
            savedTours: 2,
            completedTours: 1,
            settings: {
                emailNotifications: true,
                language: "en",
                currency: "USD",
            },
            activity: [
                { id: 1, desc: "Logged in", date: new Date().toISOString() },
                { id: 2, desc: "Viewed Destination 1", date: new Date().toISOString() },
            ],
        },
        {
            id: 2,
            name: "User2",
            image: "user2.jpg",
            role: "user",
            username: "user2",
            email: "user2@example.com",
            password: "password456",
            wishLists: [1,2],
            comments: [1, 2],
            isPro: false,
            recently: [destinations[3].id],
            messages: ["What's up"],
            savedTours: 1,
            completedTours: 0,
            settings: {
                emailNotifications: false,
                language: "mn",
                currency: "MNT",
            },
            activity: [
                { id: 3, desc: "Commented on Destination", date: new Date().toISOString() },
            ],
        },
        {
            id: 3,
            name: "User3",
            image: "user3.jpg",
            role: "user",
            username: "user3",
            email: "user3@example.com",
            password: "password789",
            wishLists: null,
            comments: null,
            isPro: false,
            recently: null,
            messages: null,
            savedTours: 0,
            completedTours: 0,
            settings: {
                emailNotifications: true,
                language: "en",
                currency: "EUR",
            },
            activity: [],
        },
        {
            id: 4,
            name: "Admin",
            image: "admin.jpg",
            role: "admin",
            username: "admin",
            email: "admin@example.com",
            password: "admin123",
            wishLists: null,
            comments: null,
            isPro: false,
            recently: null,
            messages: null,
            savedTours: 0,
            completedTours: 0,
            settings: {
                emailNotifications: true,
                language: "en",
                currency: "USD",
            },
            activity: [
                { id: 4, desc: "Approved new destination", date: new Date().toISOString() },
            ],
        },
];
